### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by IAkumaI** [cha0ran/deleteCurrentFile#1]
The command has disappeared from the palette.
Runtime status is "Not yet activated".

VS Code:
Version: 1.85.0 (Universal)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z

**Comment by cha0ran** [comment]
Okay, I'll take the time to check it out and fix it as soon as possible

**Comment by cha0ran** [comment]
This doesn't seem to be a problem with the plugin itself, it may be coming from VSCode, when I reload the window and wait a break, then reopen the file, it comes back in the command panel

**Comment by IAkumaI** [comment]
Strange. I had tried to reload VSC, it didn't help at all. Then I just found another extension: https://marketplace.visualstudio.com/items?itemName=davidalejandroaguilar.delete-file-and-keep-open
Take a look if it would help.

**Comment by cha0ran** [comment]
I think it's possible that something is wrong with the `activeEditorIsNotPreview` judgment, because I don't want to be able to delete files even in preview mode, so I added this condition, but it doesn't seem to be enforcing it correctly. I can fix it by removing this condition, but it may not be what I intended.

**Comment by cha0ran** [comment]
@IAkumaI I fixed the bug for now, you can update the plugin to confirm. If everything is working then I will close this issue.

**Comment by IAkumaI** [comment]
Yeah, it works, thanks
